apiVersion: v1
description: Kong is open-source API Gateway and Microservices Management Layer,
  delivering high performance and reliability.
engine: gotpl
home: https://getkong.org/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-medium.png
maintainers:
- name: shashiranjan84
name: kong
sources:
- https://github.com/Kong/kong
version: 0.1.0
